"""Reproducible input-snapshot package (P2-1, ENT-049/050 — the AD-014 reproducibility primitive).

Leaf tooling: ``snapshot -> {portfolio, position, valuation, holdings, marketdata, lineage, dq,
audit, db}``; nothing imports ``snapshot``. Imports NO ``calc`` symbol (readiness, not wiring);
produces NO derived number (no ``quantity x mark``, no exposure computed). P2-3 pins FX legs (via
the ``marketdata`` pure leg helper) for ``EXPOSURE_INPUT`` snapshots — still no ``calculation_run``.
P3-3 pins already-computed IMMUTABLE ``exposure_aggregate`` atoms (a models-only, function-local
read — the ``exposure`` SERVICE is never imported, it imports ``snapshot``) + ``factor`` EV
definitions for ``FACTOR_EXPOSURE_INPUT`` snapshots — pinning outputs-as-inputs, computing nothing.
P3-4 pins aligned ``factor_return`` FR windows (``COMPONENT_KIND_FACTOR_RETURN``, via the EXISTING
``marketdata.factor`` reads) for ``COVARIANCE_INPUT`` snapshots — capturing series, estimating
nothing. PM-1 pins immutable ``transaction`` rows (``COMPONENT_KIND_TRANSACTION``, the P3-3 IA-row
flavor) alongside the N boundary exposure runs' atoms + per-flow FX legs for ``RETURN_INPUT``
snapshots (the first non-risk, ``perf``-family purpose) — the flow set arrives as DATA
(``flow_txn_types``), so the ``snapshot -> ...`` fence never imports ``perf``.
"""

from __future__ import annotations

from irp_shared.snapshot.events import SNAPSHOT_CREATE_EVENT, SnapshotActor, record_snapshot_create
from irp_shared.snapshot.models import (
    COMPONENT_KIND_BENCHMARK,
    COMPONENT_KIND_BENCHMARK_RETURN,
    COMPONENT_KIND_COVARIANCE,
    COMPONENT_KIND_CURVE,
    COMPONENT_KIND_EXPOSURE,
    COMPONENT_KIND_FACTOR,
    COMPONENT_KIND_FACTOR_EXPOSURE,
    COMPONENT_KIND_FACTOR_RETURN,
    COMPONENT_KIND_FX,
    COMPONENT_KIND_PORTFOLIO_RETURN,
    COMPONENT_KIND_POSITION,
    COMPONENT_KIND_SCENARIO,
    COMPONENT_KIND_TRANSACTION,
    COMPONENT_KIND_VALUATION,
    COMPONENT_KIND_VAR,
    PURPOSE_ACTIVE_RISK_INPUT,
    PURPOSE_BENCHMARK_RELATIVE_INPUT,
    PURPOSE_COVARIANCE_INPUT,
    PURPOSE_FACTOR_EXPOSURE_INPUT,
    PURPOSE_RETURN_INPUT,
    PURPOSE_SCENARIO_INPUT,
    PURPOSE_SENSITIVITY_INPUT,
    PURPOSE_VAR_BACKTEST_INPUT,
    PURPOSE_VAR_HS_INPUT,
    PURPOSE_VAR_INPUT,
    SNAPSHOT_COMPONENT_KINDS,
    SNAPSHOT_PURPOSES,
    DatasetSnapshot,
    DatasetSnapshotComponent,
)
from irp_shared.snapshot.service import (
    ACTIVE_RISK_BINDING_PREDICATE,
    BENCHMARK_RELATIVE_BINDING_PREDICATE,
    COVARIANCE_BINDING_PREDICATE,
    DEFAULT_BINDING_PREDICATE,
    RETURN_BINDING_PREDICATE,
    VAR_BACKTEST_BINDING_PREDICATE,
    VAR_BINDING_PREDICATE,
    ActiveRiskSnapshotError,
    BenchmarkRelativeSnapshotError,
    CovarianceSnapshotError,
    CurveSelector,
    CurveSnapshotError,
    EmptySnapshotError,
    FactorExposureSnapshotError,
    ReturnSnapshotError,
    ScenarioSnapshotError,
    SnapshotNotFound,
    SnapshotPurposeError,
    VarBacktestSnapshotError,
    VarSnapshotError,
    VerifyResult,
    build_active_risk_snapshot,
    build_benchmark_relative_snapshot,
    build_covariance_snapshot,
    build_curve_snapshot,
    build_factor_exposure_snapshot,
    build_return_snapshot,
    build_scenario_snapshot,
    build_snapshot,
    build_var_backtest_snapshot,
    build_var_hs_snapshot,
    build_var_snapshot,
    list_components,
    resolve_snapshot,
    verify_snapshot,
)

__all__ = [
    "DatasetSnapshot",
    "DatasetSnapshotComponent",
    "SNAPSHOT_PURPOSES",
    "SNAPSHOT_COMPONENT_KINDS",
    "COMPONENT_KIND_FX",
    "COMPONENT_KIND_CURVE",
    "COMPONENT_KIND_POSITION",
    "COMPONENT_KIND_VALUATION",
    "PURPOSE_SENSITIVITY_INPUT",
    "SnapshotActor",
    "SNAPSHOT_CREATE_EVENT",
    "record_snapshot_create",
    "build_snapshot",
    "build_curve_snapshot",
    "CurveSelector",
    "CurveSnapshotError",
    "verify_snapshot",
    "resolve_snapshot",
    "list_components",
    "VerifyResult",
    "DEFAULT_BINDING_PREDICATE",
    "SnapshotPurposeError",
    "EmptySnapshotError",
    "SnapshotNotFound",
    "COMPONENT_KIND_EXPOSURE",
    "COMPONENT_KIND_FACTOR",
    "PURPOSE_FACTOR_EXPOSURE_INPUT",
    "build_factor_exposure_snapshot",
    "FactorExposureSnapshotError",
    "COMPONENT_KIND_FACTOR_RETURN",
    "PURPOSE_COVARIANCE_INPUT",
    "COVARIANCE_BINDING_PREDICATE",
    "build_covariance_snapshot",
    "CovarianceSnapshotError",
    "COMPONENT_KIND_FACTOR_EXPOSURE",
    "COMPONENT_KIND_COVARIANCE",
    "PURPOSE_VAR_HS_INPUT",
    "PURPOSE_VAR_INPUT",
    "VAR_BINDING_PREDICATE",
    "build_var_hs_snapshot",
    "build_var_snapshot",
    "VarSnapshotError",
    "COMPONENT_KIND_BENCHMARK",
    "PURPOSE_ACTIVE_RISK_INPUT",
    "ACTIVE_RISK_BINDING_PREDICATE",
    "build_active_risk_snapshot",
    "ActiveRiskSnapshotError",
    "COMPONENT_KIND_TRANSACTION",
    "PURPOSE_RETURN_INPUT",
    "RETURN_BINDING_PREDICATE",
    "build_return_snapshot",
    "ReturnSnapshotError",
    "COMPONENT_KIND_PORTFOLIO_RETURN",
    "COMPONENT_KIND_BENCHMARK_RETURN",
    "PURPOSE_BENCHMARK_RELATIVE_INPUT",
    "BENCHMARK_RELATIVE_BINDING_PREDICATE",
    "build_benchmark_relative_snapshot",
    "BenchmarkRelativeSnapshotError",
    "COMPONENT_KIND_SCENARIO",
    "COMPONENT_KIND_VAR",
    "PURPOSE_SCENARIO_INPUT",
    "PURPOSE_VAR_BACKTEST_INPUT",
    "VAR_BACKTEST_BINDING_PREDICATE",
    "build_scenario_snapshot",
    "build_var_backtest_snapshot",
    "ScenarioSnapshotError",
    "VarBacktestSnapshotError",
]
