"""Risk package (P3-1, ENT-028) — the first reproducible governed risk number (analytic
sensitivities: curve-node DV01 / spread-DV01).

Leaf domain package: ``risk -> {snapshot, marketdata(constants/kernel), calc, model, lineage, dq,
audit, db}``; nothing imports ``risk``. Every compute reads ONLY snapshot-pinned captured content
(never a live curve/exposure/factor/return read); no ES/scenario/stress symbol exists yet.
Run-bound + snapshot-gated + **model_version-bound** (AD-014 / FW-RUN / TR-15 / CTRL-003) — no
risk number escapes the model inventory. P3-1 analytic sensitivities (curve-intrinsic — NO
instrument/position attribution, NO interpolation, NO pricing engine); P3-3 indicator-loading
factor-exposure allocation; P3-4 equal-weighted unbiased sample covariance (ENT-051 — NO
shrinkage/EWMA/correlation output; the window is version identity; **numpy is TEST-ONLY, never a
runtime import**); P3-5 zero-mean delta-normal parametric VaR (ENT-027 `risk_result` realized —
the first derived-of-derived number; confidence/horizon/z are version identity; the PARAMETRIC
method computes NO runtime quantile — its z is registration-declared). VAR-HS-1 plain
equal-weight factor-based historical simulation (the SECOND VaR method, family
``risk.var.historical``: the EMPIRICAL lower order statistic over pinned return windows —
confidence/horizon/window/quantile-convention are version identity; NO FHS/BRW/ES/MC — those
stay separately declared versions/families).
"""

from __future__ import annotations

from irp_shared.risk.active_risk_kernel import (
    ActiveRiskKernelError,
    TeEstimate,
    compute_tracking_error,
)
from irp_shared.risk.active_risk_service import (
    ActiveRiskInputError,
    ActiveRiskNotVisible,
    ActiveRiskRunNotVisible,
    ActiveRiskRunResult,
    list_active_risks,
    resolve_active_risk,
    resolve_active_risk_run,
    run_active_risk,
)
from irp_shared.risk.bootstrap import (
    ACTIVE_RISK_METHODOLOGY_REF,
    ACTIVE_RISK_MODEL_CODE,
    COVARIANCE_METHODOLOGY_REF,
    COVARIANCE_MODEL_CODE,
    FACTOR_EXPOSURE_METHODOLOGY_REF,
    FACTOR_EXPOSURE_MODEL_CODE,
    SENSITIVITY_METHODOLOGY_REF,
    SENSITIVITY_MODEL_CODE,
    VAR_HS_METHODOLOGY_REF,
    VAR_HS_MODEL_CODE,
    VAR_METHODOLOGY_REF,
    VAR_MODEL_CODE,
    VAR_Z_SCORES,
    WINDOW_ASSUMPTION_PREFIX,
    HsVarParameters,
    ModelVersionConflictError,
    VarParameters,
    WrongModelVersionError,
    assert_model_version_of,
    declared_hs_var_parameters,
    declared_var_parameters,
    declared_window_observations,
    register_active_risk_model,
    register_covariance_model,
    register_factor_exposure_model,
    register_historical_var_model,
    register_sensitivity_model,
    register_var_model,
)
from irp_shared.risk.covariance_kernel import (
    CovarianceKernelError,
    FactorSeriesPin,
    estimate_covariance,
)
from irp_shared.risk.covariance_service import (
    CovarianceInputError,
    CovarianceNotVisible,
    CovarianceRunNotVisible,
    CovarianceRunResult,
    list_covariances,
    resolve_covariance,
    resolve_covariance_run,
    run_covariance,
)
from irp_shared.risk.events import (
    ACTIVE_RISK_METRIC_TYPES,
    METRIC_TYPE_TRACKING_ERROR,
    METRIC_TYPE_VAR_HISTORICAL,
    METRIC_TYPE_VAR_PARAMETRIC,
    METRIC_TYPES,
    RISK_ACTIVE_RISK_CREATE_EVENT_RESERVED,
    RISK_COVARIANCE_CREATE_EVENT_RESERVED,
    RISK_FACTOR_EXPOSURE_CREATE_EVENT_RESERVED,
    RISK_SENSITIVITY_CREATE_EVENT_RESERVED,
    RISK_VAR_CREATE_EVENT_RESERVED,
    RUN_TYPE_ACTIVE_RISK,
    RUN_TYPE_COVARIANCE,
    RUN_TYPE_FACTOR_EXPOSURE,
    RUN_TYPE_SENSITIVITY,
    RUN_TYPE_VAR,
    SENSITIVITY_TYPE_DV01,
    SENSITIVITY_TYPE_SPREAD_DV01,
    SENSITIVITY_TYPES,
    STATISTIC_TYPE_COVARIANCE,
    STATISTIC_TYPES,
    ActiveRiskActor,
    CovarianceActor,
    FactorExposureActor,
    SensitivityActor,
    VarActor,
)
from irp_shared.risk.factor_kernel import FactorKernelError
from irp_shared.risk.factor_service import (
    SUPPORTED_FACTOR_FAMILIES,
    FactorExposureInputError,
    FactorExposureNotVisible,
    FactorExposureRunNotVisible,
    FactorExposureRunResult,
    list_factor_exposures,
    resolve_factor_exposure,
    resolve_factor_exposure_run,
    run_factor_exposure,
)
from irp_shared.risk.kernel import SensitivityKernelError, node_dv01, node_spread_dv01
from irp_shared.risk.models import (
    ActiveRiskResult,
    CovarianceResult,
    FactorExposureResult,
    SensitivityResult,
    VarResult,
)
from irp_shared.risk.queries import (
    RISK_RUN_TYPES,
    RiskRunQueryError,
    list_risk_runs,
)
from irp_shared.risk.service import (
    SensitivityInputError,
    SensitivityNotVisible,
    SensitivityRunNotVisible,
    SensitivityRunResult,
    list_sensitivities,
    resolve_run,
    resolve_sensitivity,
    run_sensitivities,
)
from irp_shared.risk.var_hs_kernel import (
    HsVarEstimate,
    HsVarKernelError,
    compute_historical_var,
    order_statistic_index,
)
from irp_shared.risk.var_hs_service import (
    HsVarInputError,
    HsVarRunResult,
    run_var_historical,
)
from irp_shared.risk.var_kernel import VarEstimate, VarKernelError, compute_parametric_var
from irp_shared.risk.var_service import (
    VarInputError,
    VarNotVisible,
    VarRunNotVisible,
    VarRunResult,
    list_vars,
    resolve_var,
    resolve_var_run,
    run_var,
)

__all__ = [
    "HsVarEstimate",
    "HsVarKernelError",
    "HsVarInputError",
    "HsVarRunResult",
    "compute_historical_var",
    "order_statistic_index",
    "run_var_historical",
    "register_historical_var_model",
    "declared_hs_var_parameters",
    "VAR_HS_MODEL_CODE",
    "METRIC_TYPE_VAR_HISTORICAL",
    "HsVarParameters",
    "VAR_HS_METHODOLOGY_REF",
    "RISK_RUN_TYPES",
    "RiskRunQueryError",
    "list_risk_runs",
    "SensitivityResult",
    "SensitivityActor",
    "RUN_TYPE_SENSITIVITY",
    "RISK_SENSITIVITY_CREATE_EVENT_RESERVED",
    "SENSITIVITY_TYPE_DV01",
    "SENSITIVITY_TYPE_SPREAD_DV01",
    "SENSITIVITY_TYPES",
    "node_dv01",
    "node_spread_dv01",
    "SensitivityKernelError",
    "run_sensitivities",
    "list_sensitivities",
    "resolve_run",
    "resolve_sensitivity",
    "SensitivityRunResult",
    "SensitivityInputError",
    "SensitivityNotVisible",
    "SensitivityRunNotVisible",
    "register_sensitivity_model",
    "SENSITIVITY_MODEL_CODE",
    "SENSITIVITY_METHODOLOGY_REF",
    "FactorExposureResult",
    "FactorExposureActor",
    "RUN_TYPE_FACTOR_EXPOSURE",
    "RISK_FACTOR_EXPOSURE_CREATE_EVENT_RESERVED",
    "FactorKernelError",
    "run_factor_exposure",
    "list_factor_exposures",
    "resolve_factor_exposure_run",
    "resolve_factor_exposure",
    "FactorExposureRunResult",
    "FactorExposureInputError",
    "FactorExposureNotVisible",
    "FactorExposureRunNotVisible",
    "SUPPORTED_FACTOR_FAMILIES",
    "register_factor_exposure_model",
    "FACTOR_EXPOSURE_MODEL_CODE",
    "FACTOR_EXPOSURE_METHODOLOGY_REF",
    "WrongModelVersionError",
    "ModelVersionConflictError",
    "assert_model_version_of",
    "CovarianceResult",
    "CovarianceActor",
    "RUN_TYPE_COVARIANCE",
    "RISK_COVARIANCE_CREATE_EVENT_RESERVED",
    "STATISTIC_TYPE_COVARIANCE",
    "STATISTIC_TYPES",
    "CovarianceKernelError",
    "FactorSeriesPin",
    "estimate_covariance",
    "run_covariance",
    "list_covariances",
    "resolve_covariance_run",
    "resolve_covariance",
    "CovarianceRunResult",
    "CovarianceInputError",
    "CovarianceNotVisible",
    "CovarianceRunNotVisible",
    "register_covariance_model",
    "declared_window_observations",
    "COVARIANCE_MODEL_CODE",
    "COVARIANCE_METHODOLOGY_REF",
    "WINDOW_ASSUMPTION_PREFIX",
    "VarResult",
    "VarActor",
    "RUN_TYPE_VAR",
    "RISK_VAR_CREATE_EVENT_RESERVED",
    "METRIC_TYPE_VAR_PARAMETRIC",
    "METRIC_TYPES",
    "VarKernelError",
    "VarEstimate",
    "compute_parametric_var",
    "run_var",
    "list_vars",
    "resolve_var_run",
    "resolve_var",
    "VarRunResult",
    "VarInputError",
    "VarNotVisible",
    "VarRunNotVisible",
    "register_var_model",
    "declared_var_parameters",
    "VarParameters",
    "VAR_MODEL_CODE",
    "VAR_METHODOLOGY_REF",
    "VAR_Z_SCORES",
    "ActiveRiskResult",
    "ActiveRiskActor",
    "RUN_TYPE_ACTIVE_RISK",
    "RISK_ACTIVE_RISK_CREATE_EVENT_RESERVED",
    "METRIC_TYPE_TRACKING_ERROR",
    "ACTIVE_RISK_METRIC_TYPES",
    "ActiveRiskKernelError",
    "TeEstimate",
    "compute_tracking_error",
    "run_active_risk",
    "list_active_risks",
    "resolve_active_risk_run",
    "resolve_active_risk",
    "ActiveRiskRunResult",
    "ActiveRiskInputError",
    "ActiveRiskNotVisible",
    "ActiveRiskRunNotVisible",
    "register_active_risk_model",
    "ACTIVE_RISK_MODEL_CODE",
    "ACTIVE_RISK_METHODOLOGY_REF",
]
