"""The RS-1 stage-5 demo runner (OD-RS-1-E): the residual-estimator remediation — the SECOND
lifecycle turn on the living tenant.

EXTENDS the living demo tenant a FIFTH time (campaign + multifamily + stage 3 + stage 4 stay
byte-untouched). NO new model CODE is minted (both new estimators are declared VERSIONS of
``risk.proxy_weight.regression``, so the campaign/multifamily/stage-4 code-count pins hold and
the model keeps its campaign tier). The sequence:

1. Grow the equity sleeve to the EB identifiability floor: seed ``MF-EQ-C`` (a third listed
   equity; marks generated by the SAME deterministic structural-loading process as MF-1) and run
   its alpha=1 desmooth -> k=3 raw OLS -> promote (its own single-cited estimate run).
2. Register the two RS-1 versions: ``EWMA_RISKMETRICS`` (declared decay_lambda=0.94 — the
   RiskMetrics DAILY constant, honest here because the sleeve residuals ARE daily-period) and
   ``SHRINKAGE_CROSS_SECTIONAL_EB`` (method-as-identity).
3. Re-estimate ``MF-EQ-B`` under the EWMA version (fresh alpha=1 desmooth; loadings byte-equal
   to raw — the s2 decoupling; only the residual re-weighted) and RE-PROMOTE its two structural
   coefficients citing the EWMA run.
4. Run the EB shrinkage for ``MF-EQ-A`` over the 3-EQUITY comparable cohort (A/B/C raw estimate
   runs; the corporate bond DELIBERATELY EXCLUDED and asserted-raw) and RE-PROMOTE its
   structural coefficient citing the shrinkage run.
5. Fresh flagship evidence runs bound to the SAME demo-mg1 versions the AWCs sit on (the version
   grain): exposure -> loadings factor-exposure -> covariance -> total-VaR + ES-total, whose
   residual leg now pays one EB-SHRUNK + one EWMA + one raw estimate.
6. File the validation set: 2 TRIGGERED re-validations closing the raw-sample-sigma_e rider on
   the total-family AWCs (the ``hostage to the PA-3 estimate quality`` finding SUPERSEDED by the
   RS-1 closure finding; fresh conditions — the MF-1 closure-by-supersession discipline) + the
   2 INITIAL AWC dossiers for the new estimator versions.

Idempotency is REFUSE-NOT-SKIP on this stage's OWN footprint — the EWMA version label on the
proxy-weight family, probed FIRST (its registration is the first write). Requires the campaign
AND the multifamily extension (the sleeve + the raw estimates this stage transforms). The caller
owns the ONE commit. The ``stage5`` filename component of the exercising suites is LOAD-BEARING
(alpha-sorts after campaign/hg1/multifamily/stage4 — their pins are false on an extended tenant).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from decimal import ROUND_HALF_UP, Decimal

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from irp_shared.db.mixins import utcnow
from irp_shared.db.tenant import persistent_tenant_context
from irp_shared.demo.campaign import DEMO_TENANT_ID
from irp_shared.demo.dossiers import (
    RS1_CLOSURE_FINDING,
    RS1_EWMA_INITIAL,
    RS1_SHRINKAGE_INITIAL,
    RS1_TRIGGERED_DOSSIERS,
)
from irp_shared.entitlement.models import AppUser, Role, UserRole
from irp_shared.exposure import ExposureActor, run_exposure
from irp_shared.marketdata import ProxyMappingActor
from irp_shared.marketdata.models import MAPPING_METHOD_REGRESSION, Factor, ProxyMapping
from irp_shared.model.models import (
    VALIDATION_TYPE_INITIAL,
    VALIDATION_TYPE_TRIGGERED,
    Model,
    ModelLimitation,
    ModelVersion,
)
from irp_shared.model.validation import (
    ModelValidationActor,
    RecordValidationRequest,
    ValidationEvidenceInput,
    ValidationFindingInput,
    record_validation,
)
from irp_shared.perf import DesmoothedReturnActor, run_desmoothed_return
from irp_shared.perf.bootstrap import DESMOOTHED_RETURN_MODEL_CODE
from irp_shared.portfolio.models import Portfolio
from irp_shared.reference.instrument import create_instrument
from irp_shared.reference.models import Instrument
from irp_shared.reference.service import ReferenceActor
from irp_shared.risk import (
    FACTOR_EXPOSURE_LOADINGS_MODEL_CODE,
    METRIC_TYPE_ESTIMATION_SUMMARY,
    METRIC_TYPE_WEIGHT,
    PROXY_WEIGHT_MODEL_CODE,
    CovarianceActor,
    FactorExposureActor,
    ProxyWeightEstimateActor,
    ProxyWeightEstimateResult,
    VarActor,
    declared_proxy_weight_parameters,
    list_proxy_weight_results,
    promote_proxy_weight_estimate,
    register_proxy_weight_ewma_model,
    register_proxy_weight_shrinkage_eb_model,
    run_covariance,
    run_factor_exposure,
    run_proxy_weight_estimate,
    run_residual_shrinkage,
    run_var,
)
from irp_shared.valuation import create_valuation
from irp_shared.valuation.service import ValuationActor

_CODE_VERSION = "demo-rs1"
_ENVIRONMENT_ID = "demo"
_BASE_CODE_VERSION = "demo-mg1"  # the campaign versions the flagship AWCs sit on
_MF_CODE_VERSION = "demo-mf1"  # the multifamily registrations (the alpha=1 + loadings versions)
_REPORT_REF = "10_delivery_backlog/rs_1_decision_record.md"
_T0 = datetime(2024, 6, 1, tzinfo=UTC)

#: The declared EWMA decay — the RiskMetrics DAILY constant (fit on trading-day returns) applied
#: at the sleeve's CALENDAR-daily mark spacing (the distinction disclosed in the INITIAL, not
#: elided); a quarterly-appraisal series would need its OWN declared lambda.
_DECAY_LAMBDA = "0.94"

# --- The third equity (OD-RS-1-E): the SAME deterministic mark process as MF-1 (duplicated, not
# imported — the byte-frozen-fence discipline), its own structural loading + eps cycle. 12 daily
# marks over the SAME window, so the sleeve factor returns + the alpha=1 window cover it. ---
_MF_RETURN_START = date(2026, 5, 1)
_MKT_CYCLE = (
    "0.0052", "-0.0031", "0.0018", "0.0060", "-0.0044",
    "0.0011", "-0.0027", "0.0043", "-0.0016", "0.0034",
)  # fmt: skip
_MF_MARK_DATES: tuple[date, ...] = tuple(date(2026, 6, 8) + timedelta(days=i) for i in range(12))
_MF_AS_OF = _MF_MARK_DATES[-1]
_DESMOOTH_WINDOW = (date(2026, 6, 7), date(2026, 6, 20))
_SIX_DP = Decimal("0.000001")
_BASE_CURRENCY = "USD"

_EQC_CODE = "MF-EQ-C"
_EQC_NAME = "Pacific Grid Industrials common stock"
_EQC_START_MARK = "63.00"
_EQC_MARKET_LOADING = "0.8"  # the single structural loading (MF_MKT_BROAD)
_EQC_EPS = ("0.00002", "-0.00004", "0.00003", "-0.00001", "0.00005", "-0.00003", "0.00002")

_EQUITY_CODES = ("MF-EQ-A", "MF-EQ-B", _EQC_CODE)
_BOND_CODE = "MF-CR-A"
_MARKET_FACTOR = "MF_MKT_BROAD"
#: MF-EQ-B's structural factors (the MF-1 promote set, re-promoted here citing the EWMA run).
_EQB_STRUCTURAL = ("MF_MKT_BROAD", "MF_RATES_GOV")


def _dt(on: date) -> datetime:
    return datetime(on.year, on.month, on.day, 12, 0, tzinfo=UTC)


def _cycle_value(cycle: tuple[str, ...], on: date) -> Decimal:
    return Decimal(cycle[(on - _MF_RETURN_START).days % len(cycle)])


def _eqc_mark_series() -> tuple[Decimal, ...]:
    """MF-EQ-C's deterministic marks: mark_i = mark_{i-1}*(1 + L_MKT*r_MKT(d_i) + eps_i), 6dp."""
    marks = [Decimal(_EQC_START_MARK)]
    for i, on in enumerate(_MF_MARK_DATES[1:]):
        r = Decimal(_EQC_MARKET_LOADING) * _cycle_value(_MKT_CYCLE, on) + Decimal(
            _EQC_EPS[i % len(_EQC_EPS)]
        )
        marks.append((marks[-1] * (Decimal("1") + r)).quantize(_SIX_DP, rounding=ROUND_HALF_UP))
    return tuple(marks)


class DemoRs1Error(RuntimeError):
    """Stage 5 could not complete against the live tenant state (fail-loud)."""


class DemoRs1PrereqError(DemoRs1Error):
    """Stage 5 extends the LIVING tenant — it requires the MG-1 campaign AND the MF-1 sleeve
    (the raw estimates it transforms) and never bootstraps them. Run the prior stages first."""


class DemoRs1AlreadySeededError(RuntimeError):
    """Refuse-not-skip on stage 5's OWN footprint: the EWMA estimator version already exists.
    Append-only records are never double-filed; reset the schema and re-run all five stages."""

    def __init__(self) -> None:
        super().__init__(
            f"demo tenant {DEMO_TENANT_ID} already holds an EWMA estimator version of "
            f"{PROXY_WEIGHT_MODEL_CODE!r} — refusing to re-run stage 5 (reset the schema and "
            f"re-run the full five-stage sequence)."
        )


@dataclass(frozen=True)
class Rs1Stage5Summary:
    """Stage 5's end state (the load-bearing ids + the residual-story numbers)."""

    tenant_id: str
    ewma_version_id: str
    shrinkage_version_id: str
    eqc_estimate_run_id: str
    ewma_estimate_run_id: str
    shrinkage_run_id: str
    total_var_run_id: str
    es_total_run_id: str
    raw_residual_stdev: Decimal  # MF-EQ-A raw (the shrink target's before)
    shrunk_residual_stdev: Decimal  # MF-EQ-A shrunk (after)
    ewma_residual_stdev: Decimal  # MF-EQ-B EWMA
    triggered_filed: int
    initials_filed: int


# Small helpers DUPLICATED from the prior stages, not imported — those modules are byte-frozen
# fences and the raising helpers must raise stage-5-typed errors (the MF-1 adjudication, applied
# at HG-1, stage 4, and here).
def _resolve_principal(session: Session, role_code: str, label: str) -> str:
    rows = session.execute(
        select(AppUser.id)
        .join(UserRole, UserRole.user_id == AppUser.id)
        .join(Role, Role.id == UserRole.role_id)
        .where(AppUser.tenant_id == DEMO_TENANT_ID, Role.code == role_code)
    ).all()
    if len(rows) != 1:
        raise DemoRs1PrereqError(
            f"the demo tenant holds {len(rows)} {label} principal(s) — expected exactly one "
            f"from the MG-1 campaign; run it first"
        )
    return str(rows[0][0])


def _resolve_version(session: Session, code: str, code_version: str) -> ModelVersion:
    versions = (
        session.execute(
            select(ModelVersion)
            .join(Model, Model.id == ModelVersion.model_id)
            .where(
                Model.tenant_id == DEMO_TENANT_ID,
                Model.code == code,
                ModelVersion.code_version == code_version,
            )
        )
        .scalars()
        .all()
    )
    if len(versions) != 1:
        raise DemoRs1PrereqError(
            f"the demo tenant holds {len(versions)} {code_version!r} version(s) of {code!r} — "
            f"expected exactly one (a prior stage unseeded or the tenant drifted); refusing"
        )
    return versions[0]


def _resolve_alpha1_version(session: Session) -> ModelVersion:
    versions = (
        session.execute(
            select(ModelVersion)
            .join(Model, Model.id == ModelVersion.model_id)
            .where(
                Model.tenant_id == DEMO_TENANT_ID,
                Model.code == DESMOOTHED_RETURN_MODEL_CODE,
                ModelVersion.version_label == "v1-alpha1",
            )
        )
        .scalars()
        .all()
    )
    if len(versions) != 1:
        raise DemoRs1PrereqError(
            f"the demo tenant holds {len(versions)} 'v1-alpha1' desmoothing version(s) — the "
            f"MF-1 extension has not run; run the prior stages first"
        )
    return versions[0]


def _resolve_instrument(session: Session, code: str) -> str:
    inst = session.execute(
        select(Instrument.id).where(Instrument.tenant_id == DEMO_TENANT_ID, Instrument.code == code)
    ).scalar_one_or_none()
    if inst is None:
        raise DemoRs1PrereqError(
            f"the demo tenant holds no instrument {code!r} — the MF-1 sleeve has not been "
            f"seeded; run the prior stages first"
        )
    return str(inst)


def _resolve_factor_id(session: Session, factor_code: str) -> str:
    rows = (
        session.execute(
            select(Factor.id).where(
                Factor.tenant_id == DEMO_TENANT_ID,
                Factor.factor_code == factor_code,
                Factor.valid_to.is_(None),  # EV open head (Factor has no system axis)
            )
        )
        .scalars()
        .all()
    )
    if len(rows) != 1:
        raise DemoRs1PrereqError(
            f"the demo tenant holds {len(rows)} open head(s) for factor {factor_code!r} — "
            f"the MF-1 factor set is not in its seeded state; refusing"
        )
    return str(rows[0])


def _resolve_sleeve_portfolio(session: Session) -> str:
    pf = session.execute(
        select(Portfolio.id).where(
            Portfolio.tenant_id == DEMO_TENANT_ID, Portfolio.code == "DEMO-MULTIASSET"
        )
    ).scalar_one_or_none()
    if pf is None:
        raise DemoRs1PrereqError(
            "the demo tenant holds no DEMO-MULTIASSET portfolio — the MF-1 sleeve has not "
            "been seeded; run the prior stages first"
        )
    return str(pf)


def _latest_raw_summary(
    session: Session, instrument_id: str, base_version_id: str
) -> ProxyWeightEstimateResult:
    """The instrument's LATEST raw-estimate ESTIMATION_SUMMARY bound to the base (demo-mg1 RAW)
    version — the cohort member row (deterministic: system_from desc, then run id)."""
    row = (
        session.execute(
            select(ProxyWeightEstimateResult)
            .where(
                ProxyWeightEstimateResult.tenant_id == DEMO_TENANT_ID,
                ProxyWeightEstimateResult.instrument_id == instrument_id,
                ProxyWeightEstimateResult.model_version_id == base_version_id,
                ProxyWeightEstimateResult.metric_type == METRIC_TYPE_ESTIMATION_SUMMARY,
            )
            .order_by(
                ProxyWeightEstimateResult.system_from.desc(),
                ProxyWeightEstimateResult.calculation_run_id.desc(),
            )
        )
        .scalars()
        .first()
    )
    if row is None or row.residual_stdev is None:
        raise DemoRs1PrereqError(
            f"instrument {instrument_id} has no raw estimate summary bound to the base "
            f"version — the MF-1 estimation chain has not run; run the prior stages first"
        )
    return row


def _registered_limitations(session: Session, version_id: str) -> list[str]:
    return [
        r[0]
        for r in session.execute(
            select(ModelLimitation.limitation_text).where(
                ModelLimitation.model_version_id == version_id
            )
        ).all()
    ]


def _findings_from_registry(
    session: Session, version_id: str, keys: tuple[str, ...], code: str
) -> list[ValidationFindingInput]:
    """The campaign's fail-loud key mechanism (the multifamily duplication precedent — NOT
    shared machinery): each dossier finding KEY must match exactly one REGISTERED limitation
    row, whose text becomes the finding."""
    texts = _registered_limitations(session, version_id)
    findings: list[ValidationFindingInput] = []
    for key in keys:
        matches = [t for t in texts if key in t]
        if len(matches) != 1:
            raise DemoRs1Error(
                f"dossier finding key {key!r} matched {len(matches)} registered limitation "
                f"row(s) of {code} — the dossier map and the registry have drifted; refusing"
            )
        findings.append(
            ValidationFindingInput(
                finding_text=matches[0], severity="MEDIUM", authored_by="Andrew Cox"
            )
        )
    return findings


def _require_completed(result: object, label: str) -> None:
    status = getattr(result, "status", None)
    if status != "COMPLETED":
        reason = getattr(result, "failure_reason", None)
        raise DemoRs1Error(f"the {label} did not COMPLETE (status={status!r}, reason={reason!r})")


def _weight_rows(session: Session, run_id: str) -> dict[str, Decimal]:
    return {
        str(r.factor_id).lower(): r.metric_value
        for r in list_proxy_weight_results(session, run_id, acting_tenant=DEMO_TENANT_ID)
        if r.metric_type == METRIC_TYPE_WEIGHT
    }


def run_demo_rs1_stage5(session: Session) -> Rs1Stage5Summary:
    """Execute stage 5 (grow-the-cohort → register → EWMA + EB-shrink → re-promote → fresh
    flagship evidence → file). The caller owns the ONE commit."""
    detach = persistent_tenant_context(session, DEMO_TENANT_ID)
    try:
        # --- Prereq + footprint probes (refuse-not-skip, BEFORE any write) ---
        model_count = session.execute(
            select(func.count()).select_from(Model).where(Model.tenant_id == DEMO_TENANT_ID)
        ).scalar_one()
        if model_count == 0:
            raise DemoRs1PrereqError(
                f"demo tenant {DEMO_TENANT_ID} holds no model rows — the MG-1 campaign has "
                f"not run; run the prior stages first"
            )
        loadings = session.execute(
            select(Model).where(
                Model.tenant_id == DEMO_TENANT_ID,
                Model.code == FACTOR_EXPOSURE_LOADINGS_MODEL_CODE,
            )
        ).scalar_one_or_none()
        if loadings is None:
            raise DemoRs1PrereqError(
                "the demo tenant holds no loadings model — the MF-1 extension has not run; "
                "run the prior stages first"
            )
        pw_versions = (
            session.execute(
                select(ModelVersion)
                .join(Model, Model.id == ModelVersion.model_id)
                .where(Model.tenant_id == DEMO_TENANT_ID, Model.code == PROXY_WEIGHT_MODEL_CODE)
            )
            .scalars()
            .all()
        )
        for existing in pw_versions:
            if declared_proxy_weight_parameters(session, existing).estimator_convention != "RAW":
                raise DemoRs1AlreadySeededError()

        registrar_id = _resolve_principal(session, "risk_analyst_1l", "1L registrar")
        validator_id = _resolve_principal(session, "risk_manager_2l", "2L validator")

        # --- Resolve the living-sleeve state (fail-loud, never bootstrap) ---
        sleeve_pf = _resolve_sleeve_portfolio(session)
        instruments = {code: _resolve_instrument(session, code) for code in _EQUITY_CODES[:2]}
        bond_id = _resolve_instrument(session, _BOND_CODE)
        factor_ids = {
            code: _resolve_factor_id(session, code)
            for code in ("MF_MKT_BROAD", "MF_RATES_GOV", "MF_CRSPD_IG")
        }
        base_estimate_version = _resolve_version(
            session, PROXY_WEIGHT_MODEL_CODE, _BASE_CODE_VERSION
        )
        base_params = declared_proxy_weight_parameters(session, base_estimate_version)
        if base_params.min_observations is None:  # narrow for typing; RAW always carries it
            raise DemoRs1Error("the base estimate version declares no min_observations")
        alpha1_version = _resolve_alpha1_version(session)
        loadings_version = _resolve_version(
            session, FACTOR_EXPOSURE_LOADINGS_MODEL_CODE, _MF_CODE_VERSION
        )

        # --- 1: grow the cohort — seed MF-EQ-C + its raw estimation chain ---
        eqc_id = create_instrument(
            session,
            tenant_id=DEMO_TENANT_ID,
            code=_EQC_CODE,
            name=_EQC_NAME,
            asset_class="EQUITY",
            actor=ReferenceActor(actor_id=registrar_id),
        ).id
        for on, mark in zip(_MF_MARK_DATES, _eqc_mark_series(), strict=True):
            create_valuation(
                session,
                portfolio_id=sleeve_pf,
                instrument_id=eqc_id,
                valuation_date=on,
                acting_tenant=DEMO_TENANT_ID,
                actor=ValuationActor(actor_id=registrar_id),
                mark_value=mark,
                currency_code=_BASE_CURRENCY,
                valid_from=_T0,
            )
        session.flush()

        def _desmooth(instrument_id: str, label: str) -> str:
            dm = run_desmoothed_return(
                session,
                acting_tenant=DEMO_TENANT_ID,
                actor=DesmoothedReturnActor(actor_id=registrar_id),
                code_version=_CODE_VERSION,
                environment_id=_ENVIRONMENT_ID,
                model_version_id=str(alpha1_version.id),
                portfolio_id=sleeve_pf,
                instrument_id=instrument_id,
                window_start=_DESMOOTH_WINDOW[0],
                window_end=_DESMOOTH_WINDOW[1],
            )
            _require_completed(dm, label)
            return str(dm.run.run_id)

        all_factor_ids = list(factor_ids.values())
        eqc_dm = _desmooth(eqc_id, "MF-EQ-C alpha=1 desmoothed-return run")
        eqc_est = run_proxy_weight_estimate(
            session,
            acting_tenant=DEMO_TENANT_ID,
            actor=ProxyWeightEstimateActor(actor_id=registrar_id),
            code_version=_CODE_VERSION,
            environment_id=_ENVIRONMENT_ID,
            model_version_id=str(base_estimate_version.id),
            desmoothed_run_id=eqc_dm,
            factor_ids=all_factor_ids,
        )
        _require_completed(eqc_est, "MF-EQ-C raw OLS estimate run (k=3)")
        eqc_weights = _weight_rows(session, str(eqc_est.run.run_id))
        market_fid = factor_ids[_MARKET_FACTOR]
        eqc_market_weight = eqc_weights.get(market_fid.lower())
        if eqc_market_weight is None:
            raise DemoRs1Error("the MF-EQ-C estimate produced no MARKET weight row — refusing")
        promote_proxy_weight_estimate(
            session,
            private_instrument_id=eqc_id,
            factor_id=market_fid,
            weight=eqc_market_weight,
            acting_tenant=DEMO_TENANT_ID,
            actor=ProxyMappingActor(actor_id=registrar_id),
            source_calculation_run_id=str(eqc_est.run.run_id),
        )

        # --- 2: register the two RS-1 versions (the footprint's own writes) ---
        ewma_version = register_proxy_weight_ewma_model(
            session,
            tenant_id=DEMO_TENANT_ID,
            actor_id=registrar_id,
            code_version=_CODE_VERSION,
            decay_lambda=_DECAY_LAMBDA,
            min_observations=base_params.min_observations,
        )
        shrink_version = register_proxy_weight_shrinkage_eb_model(
            session,
            tenant_id=DEMO_TENANT_ID,
            actor_id=registrar_id,
            code_version=_CODE_VERSION,
        )

        # --- Resolve the cohort's raw summaries (A + B from MF-1; C from step 1) ---
        eqa_raw = _latest_raw_summary(
            session, instruments["MF-EQ-A"], str(base_estimate_version.id)
        )
        eqb_raw = _latest_raw_summary(
            session, instruments["MF-EQ-B"], str(base_estimate_version.id)
        )
        eqc_raw = _latest_raw_summary(session, str(eqc_id), str(base_estimate_version.id))

        # --- 3: the EWMA re-estimate of MF-EQ-B + its re-promotion (citing the EWMA run) ---
        eqb_dm = _desmooth(instruments["MF-EQ-B"], "MF-EQ-B alpha=1 desmoothed-return run")
        ewma_est = run_proxy_weight_estimate(
            session,
            acting_tenant=DEMO_TENANT_ID,
            actor=ProxyWeightEstimateActor(actor_id=registrar_id),
            code_version=_CODE_VERSION,
            environment_id=_ENVIRONMENT_ID,
            model_version_id=str(ewma_version.id),
            desmoothed_run_id=eqb_dm,
            factor_ids=all_factor_ids,
        )
        _require_completed(ewma_est, "MF-EQ-B EWMA estimate run")
        ewma_summary = next(
            r for r in ewma_est.rows if r.metric_type == METRIC_TYPE_ESTIMATION_SUMMARY
        )
        if ewma_summary.residual_stdev == eqb_raw.residual_stdev:
            raise DemoRs1Error(
                "the EWMA residual equals the raw residual — the convention did not bite; "
                "refusing (the demo's story would be false)"
            )
        ewma_weights = _weight_rows(session, str(ewma_est.run.run_id))
        for factor_code in _EQB_STRUCTURAL:
            fid = factor_ids[factor_code]
            weight = ewma_weights.get(fid.lower())
            if weight is None:
                raise DemoRs1Error(
                    f"the EWMA estimate produced no WEIGHT row for {factor_code} — refusing"
                )
            promote_proxy_weight_estimate(
                session,
                private_instrument_id=instruments["MF-EQ-B"],
                factor_id=fid,
                weight=weight,
                acting_tenant=DEMO_TENANT_ID,
                actor=ProxyMappingActor(actor_id=registrar_id),
                source_calculation_run_id=str(ewma_est.run.run_id),
            )

        # --- 4: the EB shrinkage of MF-EQ-A over the 3-equity cohort + its re-promotion ---
        cohort_runs = [
            str(eqa_raw.calculation_run_id),
            str(eqb_raw.calculation_run_id),
            str(eqc_raw.calculation_run_id),
        ]
        shrink = run_residual_shrinkage(
            session,
            acting_tenant=DEMO_TENANT_ID,
            actor=ProxyWeightEstimateActor(actor_id=registrar_id),
            code_version=_CODE_VERSION,
            environment_id=_ENVIRONMENT_ID,
            model_version_id=str(shrink_version.id),
            target_estimate_run_id=str(eqa_raw.calculation_run_id),
            cohort_estimate_run_ids=cohort_runs,
        )
        _require_completed(shrink, "MF-EQ-A EB shrinkage run")
        (shrunk_row,) = shrink.rows
        if shrunk_row.residual_stdev == eqa_raw.residual_stdev:
            raise DemoRs1Error(
                "the shrunk residual equals the raw residual — the EB fit did not bite; "
                "refusing (the demo's story would be false)"
            )
        eqa_raw_weights = _weight_rows(session, str(eqa_raw.calculation_run_id))
        eqa_market_weight = eqa_raw_weights.get(market_fid.lower())
        if eqa_market_weight is None:
            raise DemoRs1Error("MF-EQ-A's raw estimate has no MARKET weight row — refusing")
        promote_proxy_weight_estimate(
            session,
            private_instrument_id=instruments["MF-EQ-A"],
            factor_id=market_fid,
            weight=eqa_market_weight,  # the reviewed coefficient KEPT; the citation moves
            acting_tenant=DEMO_TENANT_ID,
            actor=ProxyMappingActor(actor_id=registrar_id),
            source_calculation_run_id=str(shrink.run.run_id),
        )

        # --- The comparable-cohort fence, asserted: the bond stays RAW (cited run untouched) ---
        bond_citations = {
            str(r.source_calculation_run_id).lower()
            for r in session.execute(
                select(ProxyMapping).where(
                    ProxyMapping.tenant_id == DEMO_TENANT_ID,
                    ProxyMapping.private_instrument_id == bond_id,
                    ProxyMapping.mapping_method == MAPPING_METHOD_REGRESSION,
                    ProxyMapping.valid_to.is_(None),
                    ProxyMapping.system_to.is_(None),
                )
            )
            .scalars()
            .all()
            if r.source_calculation_run_id is not None
        }
        touched = {str(ewma_est.run.run_id).lower(), str(shrink.run.run_id).lower()}
        if not bond_citations or bond_citations & touched:
            raise DemoRs1Error(
                "the corporate bond's open citations are missing or were touched by RS-1 runs "
                "— the comparable-cohort fence failed; refusing"
            )

        # --- 5: fresh flagship evidence bound to the demo-mg1 versions (the version grain) ---
        exposure = run_exposure(
            session,
            acting_tenant=DEMO_TENANT_ID,
            actor=ExposureActor(actor_id=registrar_id),
            code_version=_CODE_VERSION,
            environment_id=_ENVIRONMENT_ID,
            portfolio_id=sleeve_pf,
            as_of_valid_at=_dt(_MF_AS_OF),
            base_currency=_BASE_CURRENCY,
        )
        _require_completed(exposure, "sleeve exposure run")
        loadings_run = run_factor_exposure(
            session,
            acting_tenant=DEMO_TENANT_ID,
            actor=FactorExposureActor(actor_id=registrar_id),
            code_version=_CODE_VERSION,
            environment_id=_ENVIRONMENT_ID,
            model_version_id=str(loadings_version.id),
            exposure_run_id=str(exposure.run.run_id),
            factor_ids=all_factor_ids,
        )
        _require_completed(loadings_run, "loadings-family factor-exposure run")
        cov = run_covariance(
            session,
            acting_tenant=DEMO_TENANT_ID,
            actor=CovarianceActor(actor_id=registrar_id),
            code_version=_CODE_VERSION,
            environment_id=_ENVIRONMENT_ID,
            model_version_id=str(
                _resolve_version(session, "risk.covariance.sample", _BASE_CODE_VERSION).id
            ),
            factor_ids=all_factor_ids,
            as_of_valid_at=_dt(_MF_AS_OF),
        )
        _require_completed(cov, "covariance run")

        def _flagship(code: str, label: str) -> str:
            result = run_var(
                session,
                acting_tenant=DEMO_TENANT_ID,
                actor=VarActor(actor_id=registrar_id),
                code_version=_CODE_VERSION,
                environment_id=_ENVIRONMENT_ID,
                model_version_id=str(_resolve_version(session, code, _BASE_CODE_VERSION).id),
                exposure_run_id=str(loadings_run.run.run_id),
                covariance_run_id=str(cov.run.run_id),
            )
            _require_completed(result, label)
            return str(result.run.run_id)

        total_run = _flagship("risk.var.parametric_total", "RS-1 evidence total-VaR run")
        es_total_run = _flagship("risk.var.parametric_es_total", "RS-1 evidence ES-total run")

        # --- 6: file — 2 TRIGGERED closures + 2 INITIALs ---
        today = utcnow().date()
        v_actor = ModelValidationActor(actor_id=validator_id)
        document = ValidationEvidenceInput(
            evidence_type="DOCUMENT",
            reference=f"{_REPORT_REF} (OD-RS-1-E: the ratified stage-5 remediation + "
            f"re-validation shape this record transcribes)",
        )

        triggered = 0
        evidence_by_code = {
            "risk.var.parametric_total": total_run,
            "risk.var.parametric_es_total": es_total_run,
        }
        for code, dossier in RS1_TRIGGERED_DOSSIERS.items():
            version = _resolve_version(session, code, _BASE_CODE_VERSION)
            closure = ValidationFindingInput(
                finding_text=RS1_CLOSURE_FINDING, severity="LOW", authored_by="Andrew Cox"
            )
            record_validation(
                session,
                acting_tenant=DEMO_TENANT_ID,
                actor=v_actor,
                request=RecordValidationRequest(
                    model_version_id=version.id,
                    validation_type=VALIDATION_TYPE_TRIGGERED,
                    outcome=dossier.outcome,
                    scope_summary=dossier.scope_note,
                    conditions=dossier.conditions,
                    report_ref=_REPORT_REF,
                    next_review_due=today + timedelta(days=365),
                    findings=(
                        closure,
                        *_findings_from_registry(
                            session, str(version.id), dossier.finding_keys, code
                        ),
                    ),
                    evidence=(
                        ValidationEvidenceInput(
                            evidence_type="CALCULATION_RUN", run_id=evidence_by_code[code]
                        ),
                        document,
                    ),
                ),
            )
            triggered += 1

        initials = 0
        for version_obj, dossier, run_id in (
            (ewma_version, RS1_EWMA_INITIAL, str(ewma_est.run.run_id)),
            (shrink_version, RS1_SHRINKAGE_INITIAL, str(shrink.run.run_id)),
        ):
            record_validation(
                session,
                acting_tenant=DEMO_TENANT_ID,
                actor=v_actor,
                request=RecordValidationRequest(
                    model_version_id=version_obj.id,
                    validation_type=VALIDATION_TYPE_INITIAL,
                    outcome=dossier.outcome,
                    scope_summary=dossier.scope_note,
                    conditions=dossier.conditions,
                    report_ref=_REPORT_REF,
                    next_review_due=today + timedelta(days=365),
                    findings=tuple(
                        _findings_from_registry(
                            session,
                            str(version_obj.id),
                            dossier.finding_keys,
                            PROXY_WEIGHT_MODEL_CODE,
                        )
                    ),
                    evidence=(
                        ValidationEvidenceInput(evidence_type="CALCULATION_RUN", run_id=run_id),
                        document,
                    ),
                ),
            )
            initials += 1

        assert eqa_raw.residual_stdev is not None  # narrowed by _latest_raw_summary
        assert shrunk_row.residual_stdev is not None and ewma_summary.residual_stdev is not None
        return Rs1Stage5Summary(
            tenant_id=DEMO_TENANT_ID,
            ewma_version_id=str(ewma_version.id),
            shrinkage_version_id=str(shrink_version.id),
            eqc_estimate_run_id=str(eqc_est.run.run_id),
            ewma_estimate_run_id=str(ewma_est.run.run_id),
            shrinkage_run_id=str(shrink.run.run_id),
            total_var_run_id=total_run,
            es_total_run_id=es_total_run,
            raw_residual_stdev=eqa_raw.residual_stdev,
            shrunk_residual_stdev=shrunk_row.residual_stdev,
            ewma_residual_stdev=ewma_summary.residual_stdev,
            triggered_filed=triggered,
            initials_filed=initials,
        )
    finally:
        detach()
