"""I2's restore-cycle arm: a report regenerated byte-identically ACROSS a backup/restore (RPT-1).

**What this proves that the unit tier cannot.** ``test_report_generation`` proves generate →
regenerate is byte-identical inside one process against one session. That is the claim BR-9 makes,
but it is not the claim an auditor is actually relying on. They are relying on: *the report I was
shown in March can be reproduced from the archive in September, on a different machine, after the
database has been restored from backup.* Every step of that crosses a boundary the unit tier never
touches — a serialization round-trip through ``pg_dump``, a fresh process, a new connection, a
rebuilt schema.

DEP-1 is what made this testable: 10 of its 11 defects were pre-existing and invisible to a
2,980-test suite precisely because tests exercise code paths without ever starting the system.

**The hash compared is the one carried OUT OF BAND.** ``regenerate_report`` already compares against
the hash stored on the row — but that hash went through the backup too, so a dump that faithfully
preserved a wrong value would satisfy it. The ``verify`` step therefore also compares against a hash
passed on the command line, captured BEFORE the backup existed. That is the comparison that can
actually fail.

**Seeding is ARMED, not implicit.** This module writes governed rows, and it is shipped inside the
same package the migrate image installs — so it could be pointed at any database its
``DATABASE_URL`` names. ``seed`` refuses unless ``IRP_ALLOW_PROOF_SEED=1`` is set explicitly. A
proof harness that seeds silently is a data-corruption tool wearing a test's name.

Usage (inside the deployment's migrate image, see ``infra/deploy/prove_report_identity.sh``)::

    python -m irp_shared.deploy.report_identity_proof seed
    python -m irp_shared.deploy.report_identity_proof verify <report_id> <content_hash>
"""

from __future__ import annotations

import os
import sys
import uuid
from datetime import UTC, date, datetime
from decimal import Decimal

from sqlalchemy.orm import Session

from irp_shared.db.session import make_engine, make_session_factory
from irp_shared.db.tenant import set_tenant_context

#: A dedicated tenant, so the proof's rows are never mistaken for a real book's. Fixed rather than
#: random: the verify step runs in a DIFFERENT PROCESS after a restore and has to find them again.
PROOF_TENANT = "9f000000-0000-4000-8000-000000000001"
PROOF_PORTFOLIO_CODE = "RPT1-RESTORE-PROOF"
_AS_OF = date(2026, 6, 30)
_KNOWN_AT = datetime(2026, 7, 1, 12, 0, tzinfo=UTC)

_ARM_ENV = "IRP_ALLOW_PROOF_SEED"


def _session_factory():  # noqa: ANN202
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set — refusing to guess a database")
    return make_session_factory(make_engine(url))


def seed_and_generate(session: Session) -> tuple[str, str]:
    """Seed a governed concentration run and generate one report. Returns (report_id, hash)."""
    from irp_shared.calc.models import RunStatus
    from irp_shared.calc.service import create_run, update_run_status
    from irp_shared.concentration.bootstrap import (
        CONCENTRATION_METHODOLOGY_REF,
        CONCENTRATION_MODEL_CODE,
    )
    from irp_shared.concentration.events import RUN_TYPE_CONCENTRATION
    from irp_shared.concentration.models import ConcentrationResult
    from irp_shared.model.models import Model, ModelVersion
    from irp_shared.portfolio.models import Portfolio
    from irp_shared.report.service import generate_report
    from irp_shared.snapshot.models import DatasetSnapshot

    # A REAL portfolio row. ``report_generation.portfolio_id`` carries an FK to ``portfolio``, and
    # the FIRST run of this proof is what discovered that the unit tier had never satisfied it: the
    # SQLite test engine does not enforce foreign keys, so eighteen end-to-end tests had been
    # generating reports against a portfolio id that resolved to nothing. PostgreSQL refused on the
    # first attempt. Exactly the DEP-1 class — a defect no amount of test coverage could see,
    # because the tests never ran the system.
    portfolio = Portfolio(
        tenant_id=PROOF_TENANT,
        code=PROOF_PORTFOLIO_CODE,
        name="Restore-cycle identity proof",
        node_type="ACCOUNT",
        status="ACTIVE",
        record_version=1,
    )
    session.add(portfolio)
    session.flush()
    portfolio_id = str(portfolio.id)
    model = Model(
        tenant_id=PROOF_TENANT,
        code=CONCENTRATION_MODEL_CODE,
        name="Concentration (restore proof)",
        model_type="RISK",
        is_active=True,
    )
    session.add(model)
    session.flush()
    version = ModelVersion(
        tenant_id=PROOF_TENANT,
        model_id=str(model.id),
        version_label="v1",
        methodology_ref=CONCENTRATION_METHODOLOGY_REF,
        status="REGISTERED",
    )
    session.add(version)
    session.flush()

    snap = DatasetSnapshot(
        tenant_id=PROOF_TENANT,
        label="restore-proof",
        purpose="CONCENTRATION_INPUT",
        as_of_valid_at=_KNOWN_AT,
        as_of_known_at=_KNOWN_AT,
        as_of_valuation_date=_AS_OF,
        binding_predicate_version="v1",
        component_count=0,
        manifest_hash="restore-proof",
    )
    session.add(snap)
    session.flush()

    run = create_run(
        session,
        tenant_id=PROOF_TENANT,
        run_type=RUN_TYPE_CONCENTRATION,
        initiated_by="restore-proof",
        input_snapshot_id=str(snap.id),
        scope_portfolio_id=portfolio_id,
    )
    session.flush()
    scheme = str(uuid.uuid4())
    for bucket, kind, metric, detail, summary in (
        ("FINANCIALS", "DETAIL", "SHARE", Decimal("0.412300"), None),
        ("__SUMMARY__", "SUMMARY", "MAX_SHARE_SECTOR_INDUSTRY", None, Decimal("0.412300")),
    ):
        session.add(
            ConcentrationResult(
                tenant_id=PROOF_TENANT,
                calculation_run_id=run.run_id,
                input_snapshot_id=snap.id,
                model_version_id=str(version.id),
                portfolio_id=portfolio_id,
                row_kind=kind,
                dimension_kind="SECTOR_INDUSTRY",
                bucket_code=bucket,
                metric_type=metric,
                share_invested_long=detail,
                metric_value=summary,
                scheme_id=scheme,
                basis="NOT_APPLICABLE",
                gross_amount=Decimal("1000.000000"),
                long_amount=Decimal("1000.000000"),
                short_amount=Decimal("0.000000"),
                net_amount=Decimal("1000.000000"),
                denominator_basis="INVESTED_LONG",
            )
        )
    update_run_status(session, run, RunStatus.COMPLETED, actor_id="restore-proof")
    session.flush()

    row, rendered = generate_report(
        session,
        acting_tenant=PROOF_TENANT,
        actor_id="restore-proof",
        portfolio_id=portfolio_id,
        portfolio_code=PROOF_PORTFOLIO_CODE,
        as_of_date=_AS_OF,
        family_runs={"concentration": str(run.run_id)},
        generated_at=_KNOWN_AT,
    )
    print(f"RUN_ID={run.run_id}")
    print(f"PORTFOLIO_ID={portfolio_id}")
    return str(row.id), rendered.content_hash


def seed_principals(session: Session) -> dict[str, str]:
    """Three principals for the HTTP arm (RPT-2, remit I6): a maker, a viewer, and a stranger.

    **This honors — not supersedes — deploy.sh's "no invented users" precedent.** That rule
    governs DEPLOYMENT VERIFICATION: a deploy probe that manufactures an entitled user is
    manufacturing its own evidence. This module is the PROOF HARNESS, already gated behind
    ``IRP_ALLOW_PROOF_SEED`` and already writing governed rows; a proof of the entitlement fence
    needs principals on both sides of it, and seeding them here is the harness doing its stated
    job. The deploy script's verify step remains principal-free.

    The permission rows themselves are NOT created here — they must already exist from the 0002
    entitlement seed (which live-imports the catalog on ``alembic upgrade head``). Asserting that
    is itself part of the proof: a fresh deploy whose catalog is missing ``report.*`` means the
    mint never reached the database.
    """
    from sqlalchemy import select as _select

    from irp_shared.entitlement.models import (
        AppUser,
        Permission,
        Role,
        RolePermission,
        UserRole,
    )

    def _code(code: str) -> Permission:
        perm = session.execute(
            _select(Permission).where(Permission.code == code)
        ).scalar_one_or_none()
        if perm is None:
            raise RuntimeError(
                f"permission {code!r} is ABSENT from the deployed catalog — the 0002 entitlement "
                "seed did not carry the RPT-2 mint; a fresh `alembic upgrade head` should have"
            )
        return perm

    view = _code("report.view")
    generate = _code("report.generate")

    out: dict[str, str] = {}
    for name, perms in (("maker", [generate, view]), ("viewer", [view]), ("nobody", [])):
        user = AppUser(tenant_id=PROOF_TENANT, display_name=f"proof-{name}")
        role = Role(tenant_id=PROOF_TENANT, code=f"proof-{name}", name=name)
        session.add_all([user, role])
        session.flush()
        for perm in perms:
            session.add(RolePermission(role_id=role.id, permission_id=perm.id))
        session.add(UserRole(tenant_id=PROOF_TENANT, user_id=user.id, role_id=role.id))
        session.flush()
        out[name] = str(user.id)
    return out


def verify_after_restore(session: Session, *, report_id: str, expected_hash: str) -> str:
    """Regenerate the report and require BOTH hashes to agree.

    ``regenerate_report`` raises ``ReportIdentityError`` if the re-render disagrees with the hash
    STORED on the row. The additional comparison against ``expected_hash`` is what makes this a
    restore proof rather than an internal-consistency check: that value was captured before the
    archive existed and never travelled through it.
    """
    from irp_shared.report.service import regenerate_report

    rendered = regenerate_report(session, report_id=report_id, acting_tenant=PROOF_TENANT)
    if rendered.content_hash != expected_hash:
        raise RuntimeError(
            f"RESTORE-CYCLE IDENTITY FAILED: regenerated {rendered.content_hash} but the hash "
            f"captured before the backup was {expected_hash}"
        )
    return rendered.content_hash


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    command = argv[1]
    factory = _session_factory()
    session = factory()
    try:
        if command == "seed":
            if os.environ.get(_ARM_ENV) != "1":
                raise RuntimeError(
                    f"refusing to seed: set {_ARM_ENV}=1 to arm this deliberately. This writes "
                    "governed rows into whatever database DATABASE_URL names."
                )
            set_tenant_context(session, PROOF_TENANT)
            report_id, content_hash = seed_and_generate(session)
            principals = seed_principals(session)
            session.commit()
            print(f"REPORT_ID={report_id}")
            print(f"CONTENT_HASH={content_hash}")
            print(f"MAKER_ID={principals['maker']}")
            print(f"VIEWER_ID={principals['viewer']}")
            print(f"NOBODY_ID={principals['nobody']}")
            return 0
        if command == "verify":
            if len(argv) != 4:
                raise RuntimeError("usage: verify <report_id> <content_hash>")
            set_tenant_context(session, PROOF_TENANT)
            got = verify_after_restore(session, report_id=argv[2], expected_hash=argv[3])
            print(f"RESTORE_CYCLE_IDENTITY_OK={got}")
            return 0
        raise RuntimeError(f"unknown command {command!r} — expected 'seed' or 'verify'")
    finally:
        session.close()


if __name__ == "__main__":  # pragma: no cover - the container entry point
    sys.exit(main(sys.argv))
